# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Torchbearer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Torchbearer
  pod 'MapboxCoreNavigation', '~> 0.2.1'

  target 'TorchbearerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
